name: Maven Build
on:
  push:
    branches:
      - main
jobs:
  compile:
    name: "Maven Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: API Tests
        run: mvn compile
